In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('Maternal_Anemia.csv')

In [4]:
df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Aruba,ABW,Prevalence of anemia among pregnant women (%),SH.PRG.ANEM,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,Prevalence of anemia among pregnant women (%),SH.PRG.ANEM,NaN,NaN,NaN,NaN,NaN,NaN,...,38.084036,38.150456,38.181797,38.188109,38.264416,38.412547,38.742843,39.132490,NaN,NaN
2,Afghanistan,AFG,Prevalence of anemia among pregnant women (%),SH.PRG.ANEM,NaN,NaN,NaN,NaN,NaN,NaN,...,32.700000,32.500000,32.200000,32.000000,31.700000,31.500000,31.500000,31.600000,NaN,NaN
3,Africa Western and Central,AFW,Prevalence of anemia among pregnant women (%),SH.PRG.ANEM,NaN,NaN,NaN,NaN,NaN,NaN,...,50.255739,49.952560,49.724108,49.462210,49.236998,49.001597,48.953077,48.976387,NaN,NaN
4,Angola,AGO,Prevalence of anemia among pregnant women (%),SH.PRG.ANEM,NaN,NaN,NaN,NaN,NaN,NaN,...,45.300000,45.500000,45.600000,45.500000,45.500000,45.500000,45.700000,45.900000,NaN,NaN

In [5]:
df.shape

(266, 70)

In [6]:
df.drop(columns=['Indicator Name','Indicator Code'], inplace=True)

In [7]:
df['Country Name'] = df['Country Name'].str.encode('latin1').str.decode('utf-8')

In [8]:
df.head()

,Country Name,Country Code,1960,1961,1962,1963,1964,1965,1966,1967,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,38.084036,38.150456,38.181797,38.188109,38.264416,38.412547,38.742843,39.132490,NaN,NaN
2,Afghanistan,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,32.700000,32.500000,32.200000,32.000000,31.700000,31.500000,31.500000,31.600000,NaN,NaN
3,Africa Western and Central,AFW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,50.255739,49.952560,49.724108,49.462210,49.236998,49.001597,48.953077,48.976387,NaN,NaN
4,Angola,AGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,45.300000,45.500000,45.600000,45.500000,45.500000,45.500000,45.700000,45.900000,NaN,NaN

In [9]:
country_codes = [
"AFG","ALB","DZA","AND","AGO","ATG","ARG","ARM","AUS","AUT","AZE","BHS","BHR","BGD",
"BRB","BLR","BEL","BLZ","BEN","BTN","BOL","BIH","BWA","BRA","BRN","BGR","BFA","BDI",
"CPV","KHM","CMR","CAN","CAF","TCD","CHL","CHN","COL","COM","COG","CRI","HRV","CUB",
"CYP","CZE","CIV","COD","DNK","DJI","DMA","DOM","ECU","EGY","SLV","GNQ","ERI","EST",
"SWZ","ETH","FJI","FIN","FRA","GAB","GMB","GEO","DEU","GHA","GRC","GRD","GTM","GIN",
"GNB","GUY","HTI","HND","HUN","ISL","IND","IDN","IRN","IRQ","IRL","ISR","ITA","JAM",
"JPN","JOR","KAZ","KEN","KIR","KWT","KGZ","LAO","LVA","LBN","LSO","LBR","LBY","LIE",
"LTU","LUX","MDG","MWI","MYS","MDV","MLI","MLT","MHL","MRT","MUS","MEX","FSM","MDA",
"MCO","MNG","MNE","MAR","MOZ","MMR","NAM","NRU","NPL","NLD","NZL","NIC","NER","NGA",
"PRK","MKD","NOR","OMN","PAK","PLW","PSE","PAN","PNG","PRY","PER","PHL","POL","PRT",
"QAT","ROU","RUS","RWA","KNA","LCA","VCT","WSM","SMR","STP","SAU","SEN","SRB","SYC",
"SLE","SGP","SVK","SVN","SLB","SOM","ZAF","KOR","SSD","ESP","LKA","SDN","SUR","SWE",
"CHE","SYR","TJK","TZA","THA","TLS","TGO","TON","TTO","TUN","TKM","TUV","TUR","UGA",
"UKR","ARE","GBR","USA","URY","UZB","VUT","VAT","VEN","VNM","YEM","ZMB","ZWE"
]

In [10]:
len(country_codes)

195

In [11]:
df_filtered = df[df['Country Code'].isin(country_codes)]

In [25]:
years = [str(year) for year in range(2000,2024)]
df_final = df_filtered[['Country Name','Country Code'] + years]

In [26]:
df_final = df_final.sort_values(by='Country Name').reset_index(drop=True)

In [27]:
df_final.head()

,Country Name,Country Code,2000,2001,2002,2003,2004,2005,2006,2007,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Afghanistan,AFG,38.6,38.2,37.8,37.4,37.0,36.6,36.2,35.7,...,33.2,32.9,32.7,32.5,32.2,32.0,31.7,31.5,31.5,31.6
1,Albania,ALB,28.4,27.6,26.9,26.2,25.6,24.9,24.4,23.8,...,23.2,23.5,23.9,24.2,24.5,24.7,24.9,25.1,25.3,25.5
2,Algeria,DZA,36.1,35.8,35.5,35.3,35.1,34.9,34.7,34.5,...,33.2,33.2,33.3,33.4,33.6,33.8,34.1,34.3,34.8,35.2
3,Andorra,AND,21.0,20.5,20.1,19.7,19.4,19.1,18.8,18.5,...,17.2,17.0,16.9,16.7,16.6,16.4,16.3,16.3,16.3,16.3
4,Angola,AGO,52.3,51.8,51.3,50.7,50.1,49.5,48.8,48.2,...,45.2,45.2,45.3,45.5,45.6,45.5,45.5,45.5,45.7,45.9

In [28]:
df_final.size

5044

In [37]:
df_final.shape

(194, 28)

In [30]:
for year in years:
    temp_df = df_final[['Country Name', 'Country Code', year]].copy()
    
    # Rename column to something clean
    temp_df = temp_df.rename(columns={year: 'Prevalance of Anemia %'})

    # ADD year column 
    temp_df['Year'] = int(year)

    # Reorder columns
    temp_df = temp_df[['Country Name', 'Country Code', 'Year', 'Prevalance of Anemia %']]
    
    # Save file
    temp_df.to_csv(f"{year}_maternal_anemia.csv", index=False)

In [30]:
df_final.to_csv("Cleaned_Maternal_Anemia_2000_2023.csv", index=False)

Find Missing values for each country

In [31]:
missing_count = df_final[years].isnull().sum(axis=1)

df_final_missing_summary = df_final[['Country Name', 'Country Code']].copy()
df_final_missing_summary['Missing Count'] = missing_count

# Sort by highest missing
df_final_missing_summary = df_final_missing_summary.sort_values(by='Missing Count', ascending=False)

print(df_final_missing_summary)

           Country Name Country Code  Missing Count
99        Liechtenstein          LIE             24
125           Nicaragua          NIC             24
2               Algeria          DZA              0
3               Andorra          AND              0
4                Angola          AGO              0
..                  ...          ...            ...
189            Viet Nam          VNM              0
190  West Bank and Gaza          PSE              0
191         Yemen, Rep.          YEM              0
192              Zambia          ZMB              0
193            Zimbabwe          ZWE              0

[194 rows x 3 columns]

In [32]:
missing_years = df_final[years].isnull()

df_final['Missing Years'] = missing_years.apply(
    lambda row: [year for year in years if row[year]], axis=1
)

result = df_final[['Country Name', 'Country Code', 'Missing Years']]

print(result)

           Country Name Country Code Missing Years
0           Afghanistan          AFG            []
1               Albania          ALB            []
2               Algeria          DZA            []
3               Andorra          AND            []
4                Angola          AGO            []
..                  ...          ...           ...
189            Viet Nam          VNM            []
190  West Bank and Gaza          PSE            []
191         Yemen, Rep.          YEM            []
192              Zambia          ZMB            []
193            Zimbabwe          ZWE            []

[194 rows x 3 columns]

In [35]:
df_final['Missing Count'] = df_final[years].isnull().sum(axis=1)

df_final['Missing Years'] = df_final[years].isnull().apply(
    lambda row: [year for year in years if row[year]], axis=1
)
df_missing_only = df_final[df_final['Missing Count'] > 0]
final_missing = df_missing_only[['Country Name', 'Country Code', 'Missing Count', 'Missing Years']]

print(final_missing)

      Country Name Country Code  Missing Count  \
99   Liechtenstein          LIE             24
125      Nicaragua          NIC             24

                                         Missing Years
99   [2000, 2001, 2002, 2003, 2004, 2005, 2006, 200...
125  [2000, 2001, 2002, 2003, 2004, 2005, 2006, 200...

In [36]:
final_missing.to_csv("missing_data_Predictor-08_report.csv", index=False)